#pragma once

// Used for event handling for this essential.
enum CobraWidgetID
{
	CREATE_NEW_PROJECT_BUTTON_ID = 2, 
	RUN_CODE_MENUITEM_ID, 
	SET_DARK_THEME_MENUITEM_ID, 
	SET_LIGHT_THEME_MENUITEM_ID,
	CODEBODY_IDE_ID, 
	OPEN_PROJECT_BUTTON_ID, 
	FILE_TREE_IDE_ID, 
	SET_FONT_MENUITEM_ID, 
	STOP_FINDING_MENUITEM_ID, 
	FINDANDREPLACE_DIALOG_OK_ID, 
	FINDANDREPLACE_DIALOG_CLOSE_ID
};
